openapi: 3.0.3
info:
  title: ZKorum
  description: ZKorum backend
  version: 1.0.0
components:
  schemas: {}
paths:
  /auth/authenticate:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  maxLength: 254
                  minLength: 1
                  description: Email address
                didExchange:
                  type: string
                  maxLength: 1000
                  description: Decentralized Identifier with did:key method
                isRequestingNewCode:
                  type: boolean
              required:
                - email
                - didExchange
                - isRequestingNewCode
              additionalProperties: false
        required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  codeExpiry:
                    type: string
                    format: date-time
                  nextCodeSoonestTime:
                    type: string
                    format: date-time
                required:
                  - codeExpiry
                  - nextCodeSoonestTime
                additionalProperties: false
        "409":
          description: Default Response
          content:
            application/json:
              schema:
                anyOf:
                  - type: object
                    properties:
                      reason:
                        type: string
                        enum:
                          - awaiting_syncing
                      userId:
                        type: string
                        format: uuid
                        minLength: 1
                    required:
                      - reason
                      - userId
                    additionalProperties: false
                  - type: object
                    properties:
                      reason:
                        type: string
                        enum:
                          - already_logged_in
                      userId:
                        type: string
                        format: uuid
                        minLength: 1
                      encryptedSymmKey:
                        type: string
                      syncingDevices:
                        type: array
                        items:
                          type: string
                      emailCredentialsPerEmail:
                        type: object
                        additionalProperties:
                          type: object
                          properties:
                            active:
                              type: string
                            revoked:
                              type: array
                              items:
                                type: string
                          required:
                            - revoked
                          additionalProperties: false
                      secretCredentialsPerType:
                        type: object
                        additionalProperties:
                          type: object
                          properties:
                            active:
                              type: string
                            revoked:
                              type: array
                              items:
                                type: string
                          required:
                            - revoked
                          additionalProperties: false
                    required:
                      - reason
                      - userId
                      - encryptedSymmKey
                      - syncingDevices
                      - emailCredentialsPerEmail
                      - secretCredentialsPerType
                    additionalProperties: false
  /auth/verifyOtp:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: number
                  minimum: 0
                  maximum: 999999
                encryptedSymmKey:
                  type: string
              required:
                - code
                - encryptedSymmKey
              additionalProperties: false
        required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                anyOf:
                  - type: object
                    properties:
                      success:
                        type: boolean
                        enum:
                          - true
                      userId:
                        type: string
                        format: uuid
                        minLength: 1
                      encryptedSymmKey:
                        type: string
                      syncingDevices:
                        type: array
                        items:
                          type: string
                      emailCredentialsPerEmail:
                        type: object
                        additionalProperties:
                          type: object
                          properties:
                            active:
                              type: string
                            revoked:
                              type: array
                              items:
                                type: string
                          required:
                            - revoked
                          additionalProperties: false
                      secretCredentialsPerType:
                        type: object
                        additionalProperties:
                          type: object
                          properties:
                            active:
                              type: string
                            revoked:
                              type: array
                              items:
                                type: string
                          required:
                            - revoked
                          additionalProperties: false
                    required:
                      - success
                      - userId
                      - syncingDevices
                      - emailCredentialsPerEmail
                      - secretCredentialsPerType
                    additionalProperties: false
                  - type: object
                    properties:
                      success:
                        type: boolean
                        enum:
                          - false
                      reason:
                        type: string
                        enum:
                          - expired_code
                          - wrong_guess
                          - too_many_wrong_guess
                    required:
                      - success
                      - reason
                    additionalProperties: false
        "409":
          description: Default Response
          content:
            application/json:
              schema:
                anyOf:
                  - type: object
                    properties:
                      reason:
                        type: string
                        enum:
                          - awaiting_syncing
                      userId:
                        type: string
                        format: uuid
                        minLength: 1
                    required:
                      - reason
                      - userId
                    additionalProperties: false
                  - type: object
                    properties:
                      reason:
                        type: string
                        enum:
                          - already_logged_in
                      userId:
                        type: string
                        format: uuid
                        minLength: 1
                      encryptedSymmKey:
                        type: string
                      syncingDevices:
                        type: array
                        items:
                          type: string
                      emailCredentialsPerEmail:
                        type: object
                        additionalProperties:
                          type: object
                          properties:
                            active:
                              type: string
                            revoked:
                              type: array
                              items:
                                type: string
                          required:
                            - revoked
                          additionalProperties: false
                      secretCredentialsPerType:
                        type: object
                        additionalProperties:
                          type: object
                          properties:
                            active:
                              type: string
                            revoked:
                              type: array
                              items:
                                type: string
                          required:
                            - revoked
                          additionalProperties: false
                    required:
                      - reason
                      - userId
                      - encryptedSymmKey
                      - syncingDevices
                      - emailCredentialsPerEmail
                      - secretCredentialsPerType
                    additionalProperties: false
  /auth/logout:
    post:
      responses:
        "200":
          description: Default Response
  /auth/sync:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  maxLength: 254
                  minLength: 1
                  description: Email address
                secretBlindedCredentialRequest:
                  type: string
              required:
                - email
              additionalProperties: false
        required: true
      responses:
        "409":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  reason:
                    type: string
                    enum:
                      - already_syncing
                  userId:
                    type: string
                    format: uuid
                    minLength: 1
                required:
                  - reason
                  - userId
                additionalProperties: false
  /credentials/get:
    post:
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  emailCredentialsPerEmail:
                    type: object
                    additionalProperties:
                      type: object
                      properties:
                        active:
                          type: string
                        revoked:
                          type: array
                          items:
                            type: string
                      required:
                        - revoked
                      additionalProperties: false
                  secretCredentialsPerType:
                    type: object
                    additionalProperties:
                      type: object
                      properties:
                        active:
                          type: string
                        revoked:
                          type: array
                          items:
                            type: string
                      required:
                        - revoked
                      additionalProperties: false
                required:
                  - emailCredentialsPerEmail
                  - secretCredentialsPerType
                additionalProperties: false
servers: []
